-- ============================================================
-- ANALITIKA MG — Supabase schema setup
-- Run this once in Supabase SQL Editor (Settings → SQL Editor)
-- ============================================================


-- ---- 1. UNITS table (existing) ----
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  parent text,
  lat float8,
  lon float8,
  today int default 0,
  m30 int default 0,
  ytd int default 0,
  color text,
  inspectors text,
  last_check date
);
alter table units enable row level security;
create policy "units_select" on units for select using (auth.role() = 'authenticated');
create policy "units_insert" on units for insert with check (auth.role() = 'authenticated');
create policy "units_update" on units for update using (auth.role() = 'authenticated');


-- ---- 2. PROFILES table (roles) ----
create table if not exists profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  role text not null default 'viewer' check (role in ('admin', 'viewer')),
  full_name text,
  created_at timestamptz default now() not null
);
alter table profiles enable row level security;

-- Any authenticated user can read profiles
create policy "profiles_select" on profiles
  for select to authenticated using (true);

-- Users can update their own name (but NOT role)
create policy "profiles_update_self" on profiles
  for update to authenticated
  using (auth.uid() = id)
  with check (role = (select role from profiles where id = auth.uid()));

-- Admins can update any profile (including role)
create policy "profiles_admin_update" on profiles
  for update to authenticated
  using ((select role from profiles where id = auth.uid()) = 'admin');


-- ---- 3. Auto-create profile on signup ----
create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();


-- ---- 4. UNIT_CASES table (curator cases) ----
create table if not exists unit_cases (
  id uuid default gen_random_uuid() primary key,
  unit_id text not null,
  unit_name text,
  title text not null,
  description text,
  case_date date,
  created_at timestamptz default now() not null,
  created_by uuid references auth.users(id) on delete set null
);
alter table unit_cases enable row level security;

-- All authenticated users can READ cases
create policy "cases_select" on unit_cases
  for select to authenticated using (true);

-- Only admins can INSERT
create policy "cases_insert" on unit_cases
  for insert to authenticated
  with check ((select role from profiles where id = auth.uid()) = 'admin');

-- Only admins can UPDATE
create policy "cases_update" on unit_cases
  for update to authenticated
  using ((select role from profiles where id = auth.uid()) = 'admin');

-- Only admins can DELETE
create policy "cases_delete" on unit_cases
  for delete to authenticated
  using ((select role from profiles where id = auth.uid()) = 'admin');


-- ============================================================
-- HOW TO CREATE USERS & SET ADMIN ROLE:
--
-- 1. Go to Supabase Dashboard → Authentication → Users
-- 2. Click "Invite user" or "Add user" — enter email + password
-- 3. After user is created, run this query to make them admin:
--
--    update profiles set role = 'admin' where id = '<user-uuid>';
--
-- 4. To get user UUID:
--    select id, email from auth.users where email = 'admin@example.com';
--
-- ============================================================


-- ---- 5. Supabase Auth Email redirect URLs ----
-- In Supabase Dashboard → Authentication → URL Configuration:
-- Add to "Redirect URLs": https://analitika.pages.dev
-- Site URL: https://analitika.pages.dev
-- ============================================================
