-- Run this in Supabase SQL editor once
create table if not exists units (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  parent text,
  lat float8,
  lon float8,
  today int default 0,
  m30 int default 0,
  ytd int default 0,
  color text,
  inspectors text,
  last_check date
);
alter table units enable row level security;
create policy "units read for all" on units for select using (true);
create policy "units insert for all" on units for insert with check (true);
create policy "units update for all" on units for update using (true);
